# Generated by Django 5.1.6 on 2025-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serviceproductusage",
            name="quantity_used",
            field=models.FloatField(),
        ),
    ]
